name: Upload to PyPi
on:
  release:
    types: [published]

jobs:
    pypi-publish:
      name: Upload release to PyPI
      runs-on: ubuntu-latest
      permissions:
        id-token: write
      steps:    
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
          enable-cache: false
      - name: Build
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
